### PR TITLE
Audio additional features and removed wall times for graphs

### PR DESCRIPTION
**Pull request by mkusman1**

### CODE REVIEW

**Comment by mkusman1** [comment]
@PSSF23 I made corrections based on your feedback. Please let me know if it works.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
Some needs in `audio_spec_mel_mfcc.py`:

- Why commenting out `audio_toolbox` import? The script won't run without the functions.
- Why different `samples_space` and `combinations`? Those should be **fixed** to 45 combinations and 6 increments from 10 to 480.
- All spellings of "spectrogram" are wrong.
- Style the file with `black` and remove commented codes.
- No need to change "-m" to "--m." And adding another argument for feature type would be ideal. Also include example usage or instruction.

**Comment by PSSF23** [comment]
@mkusman1 Which machine did you run your wall times on?

**Comment by sampan501** [comment]
Also, comments please explaining lines of the code

**Review by PSSF23 — COMMENTED** [review]
One more modification needed: adding "accuracy" to the y-axes.

**Review by PSSF23 — COMMENTED** [review]
Fixed y-axes

**Review by PSSF23 — APPROVED** [review]

**Pull request merged**
